[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
    "forge-std/=./lib/forge-std/src/",
    "@solmate/contracts/=lib/solmate/src",
    "@openzeppelin/=./lib/openzeppelin-contracts/",
    "@uniswap/v2-core/contracts/=lib/v2-core/contracts/",
    "@uniswap/v2-periphery/contracts/=lib/v2-periphery/contracts/",
    "@uniswap/lib/contracts/=lib/solidity-lib/contracts/"
]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
unchecked_cheatcode_artifacts = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
local = "http://localhost:8545"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
