[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
    "@uniswap/uniswapv2-core/=lib/uniswap-v2-core/",
    "uniswap-v2-periphery/=lib/uniswap-v2-periphery/",
    "@aerodrome/=./lib/contracts/",
    "@openzeppelin/=./lib/openzeppelin-contracts/",
    "forge-std/=./lib/forge-std/src/"
]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
local = "http://localhost:8545"
