[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
    "@uniswap/v2-core/=./lib/v2-core/",
    "@uniswap/v2-periphery/=./lib/v2-periphery/",
    "@openzeppelin/=./lib/openzeppelin-contracts/",
    "forge-std/=./lib/forge-std/src/"
]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

# Add separate profiles for different Solidity versions
[profile.v2-core]
src = "./lib/v2-core/contracts"
out = "out"
libs = ["lib"]
solc = "0.5.16"

[profile.v2-periphery]
src = "./lib/v2-periphery/contracts" 
out = "out"
libs = ["lib"]
solc = "0.6.6"


[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
local = "http://localhost:8545"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
